param(
    [string]$FuelTankBaseToken = "Ba0DbuHxaaonj2sxT4tcEwWonZf",

    [string]$FuelTankTableId = "tbloO6EEgyXFrwFG",

    [string]$RecordId = "",

    [Parameter(Mandatory = $true)]
    [string]$FuelTankId,

    [Parameter(Mandatory = $true)]
    [string]$SessionId,

    [Parameter(Mandatory = $true)]
    [string]$CustomerId,

    [Parameter(Mandatory = $true)]
    [string]$SalesId,

    [Parameter(Mandatory = $true)]
    [string]$WorkDate,

    [Parameter(Mandatory = $true)]
    [string]$StartSnapshotRef,

    [string]$NewInputsToday = "",

    [string]$NewInputsTodayFile = "",

    [ValidateSet("active", "closed", "stale")]
    [string]$Status = "active",

    [string]$UpdatedAt = "",

    [ValidateSet("user", "bot")]
    [string]$As = "bot",

    [switch]$UseFieldIds,

    [switch]$DryRun
)

$ErrorActionPreference = "Stop"
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
$OutputEncoding = [System.Text.Encoding]::UTF8

function Read-OptionalText {
    param(
        [string]$Value,
        [string]$Path
    )

    if (-not [string]::IsNullOrWhiteSpace($Path)) {
        if (-not (Test-Path -LiteralPath $Path)) {
            throw "File does not exist: $Path"
        }
        return [System.IO.File]::ReadAllText((Resolve-Path -LiteralPath $Path).Path, [System.Text.Encoding]::UTF8)
    }
    return $Value
}

function Add-FieldValue {
    param(
        [System.Collections.IDictionary]$Payload,
        [string]$FieldName,
        [object]$Value
    )

    $key = $FieldName
    if ($UseFieldIds) {
        $key = $FieldMap[$FieldName]
    }
    $Payload[$key] = $Value
}

if ([string]::IsNullOrWhiteSpace($FuelTankId)) {
    throw "FuelTankId is required."
}
if ([string]::IsNullOrWhiteSpace($SessionId)) {
    throw "SessionId is required."
}
if ([string]::IsNullOrWhiteSpace($CustomerId)) {
    throw "CustomerId is required. Run B-SK02 or B-SK03 before building FuelTank."
}
if ([string]::IsNullOrWhiteSpace($SalesId)) {
    throw "SalesId is required."
}
if ($WorkDate -notmatch '^\d{4}-\d{2}-\d{2}$') {
    throw "WorkDate must be yyyy-MM-dd."
}
if ([string]::IsNullOrWhiteSpace($StartSnapshotRef)) {
    throw "StartSnapshotRef is required."
}
if ([string]::IsNullOrWhiteSpace($UpdatedAt)) {
    $UpdatedAt = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")
}
else {
    $UpdatedAt = ([datetime]::Parse($UpdatedAt)).ToString("yyyy-MM-dd HH:mm:ss")
}

$newInputsText = Read-OptionalText -Value $NewInputsToday -Path $NewInputsTodayFile
if ([string]::IsNullOrWhiteSpace($newInputsText)) {
    throw "NewInputsToday or NewInputsTodayFile is required."
}

try {
    $newInputsObj = $newInputsText | ConvertFrom-Json
}
catch {
    throw "NewInputsToday must be JSON generated by build-new-inputs-today.ps1."
}
if ([string]$newInputsObj.schema -ne "b.fuel_tank_inputs.v1") {
    throw "NewInputsToday schema must be b.fuel_tank_inputs.v1."
}
if ([string]$newInputsObj.mode -ne "append_only_fuel_deposit") {
    throw "NewInputsToday mode must be append_only_fuel_deposit."
}
if ($null -eq $newInputsObj.fuel_events -or @($newInputsObj.fuel_events).Count -lt 1) {
    throw "NewInputsToday must include at least one fuel_event extracted from session/material inputs."
}
if ($null -eq $newInputsObj.deposit_policy -or [bool]$newInputsObj.deposit_policy.append_only -ne $true) {
    throw "NewInputsToday must declare deposit_policy.append_only=true."
}

$TableContract = [ordered]@{
    line = "B"
    table_name = "02_fuel_tank"
    base_token_default = "Ba0DbuHxaaonj2sxT4tcEwWonZf"
    table_id_default = "tbloO6EEgyXFrwFG"
}

$FieldMap = [ordered]@{
    fuel_tank_id = "fldP3TwKXy"
    session_id = "fld79G5XL4"
    customer_id = "fld1HVBbuz"
    sales_id = "fldiRPQEzA"
    work_date = "fldifwfyTK"
    start_snapshot_ref = "fldo6WNlQY"
    new_inputs_today = "fldFwqPeqq"
    status = "fldTaPxssT"
    updated_at = "fldGlRTEUC"
}

$ForbiddenFieldNames = @(
    "fuel_sufficiency",
    "missing_information",
    "pending_confirmations",
    "current_customer_stage",
    "objections",
    "buying_signals",
    "risk_flags",
    "confidence_score",
    "should_trigger_dline",
    "trigger_reason",
    "recommended_dline_skills",
    "generated_artifact_ids",
    "used_artifact_ids",
    "remark"
)

$payload = [ordered]@{}
Add-FieldValue -Payload $payload -FieldName "fuel_tank_id" -Value $FuelTankId
Add-FieldValue -Payload $payload -FieldName "session_id" -Value $SessionId
Add-FieldValue -Payload $payload -FieldName "customer_id" -Value $CustomerId
Add-FieldValue -Payload $payload -FieldName "sales_id" -Value $SalesId
Add-FieldValue -Payload $payload -FieldName "work_date" -Value $WorkDate
Add-FieldValue -Payload $payload -FieldName "start_snapshot_ref" -Value $StartSnapshotRef
Add-FieldValue -Payload $payload -FieldName "new_inputs_today" -Value (($newInputsObj | ConvertTo-Json -Compress -Depth 20))
Add-FieldValue -Payload $payload -FieldName "status" -Value $Status
Add-FieldValue -Payload $payload -FieldName "updated_at" -Value $UpdatedAt

if ($DryRun) {
    [ordered]@{
        dry_run = $true
        operation = $(if ([string]::IsNullOrWhiteSpace($RecordId)) { "create" } else { "update" })
        record_id = $RecordId
        base_token = $FuelTankBaseToken
        table_id = $FuelTankTableId
        use_field_ids = [bool]$UseFieldIds
        allowed_write_fields = @($FieldMap.Keys)
        forbidden_fields = $ForbiddenFieldNames
        payload = $payload
    } | ConvertTo-Json -Depth 24
    return
}

$json = $payload | ConvertTo-Json -Compress -Depth 24
$tmpDirName = ".lark-tmp"
$tmpDir = Join-Path (Get-Location).Path $tmpDirName
$jsonFileName = "$([System.Guid]::NewGuid().ToString('N')).json"
$jsonFile = Join-Path $tmpDir $jsonFileName
$jsonFileArg = "@$tmpDirName/$jsonFileName"

try {
    if (-not (Test-Path -LiteralPath $tmpDir)) {
        New-Item -ItemType Directory -Path $tmpDir -Force | Out-Null
    }
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($jsonFile, $json, $utf8NoBom)

    $argsList = @(
        "base", "+record-upsert",
        "--base-token", $FuelTankBaseToken,
        "--table-id", $FuelTankTableId,
        "--json", $jsonFileArg,
        "--as", $As
    )
    if (-not [string]::IsNullOrWhiteSpace($RecordId)) {
        $argsList += @("--record-id", $RecordId)
    }

    & lark-cli @argsList
}
finally {
    if (Test-Path -LiteralPath $jsonFile) {
        Remove-Item -LiteralPath $jsonFile -Force -ErrorAction SilentlyContinue
    }
    if (Test-Path -LiteralPath $tmpDir) {
        $remaining = @(Get-ChildItem -LiteralPath $tmpDir -Force -ErrorAction SilentlyContinue)
        if ($remaining.Count -eq 0) {
            Remove-Item -LiteralPath $tmpDir -Force -ErrorAction SilentlyContinue
        }
    }
}
